# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'PseudoPieGraphExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PseudoPieGraphExample

  pod 'PseudoPieGraph'

end